import "./globals.css";

export const metadata = {
  title: "STRAI ",
  description: "Stategic AI, Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
